network:
  ethernets:
    ens2:
        dhcp4: true
        dhcp6: true
    ens3:
        dhcp4: false
        addresses:
        - 10.10.0.1/24
        #gateway4: 192.168.255.1
        #gateway6: 2001:db8:2005::1
        #nameservers:
            #addresses:
        routes:
        - to: 10.10.20.0/24
          via: 10.10.0.254
  version: 2
