---
- hosts: all
  gather_facts: false
  tasks:
    - name: create time
      set_fact:
        exe_date: "{{ lookup('pipe', 'date +%Y%m%d_%H%M_%S') }}"
      run_once: true

    - name: create parent directory
      set_fact:
        logdir_date: "{{ inventory_dir }}/log/log_{{ exe_date }}"
      run_once: true
  
    - name: create directory for log
      file:
        path: "{{ logdir_date }}/"
        state: directory
      register: logdir
      delegate_to: localhost
      run_once: true

- name: ios section
  hosts: ios
  gather_facts: false
  roles:
    - { role: get_ios_command, when: "'ios' in groups and inventory_hostname in groups['ios']" }
    - { role: save_cisco_command_logdir, when: "'ios' in groups and inventory_hostname in groups['ios']" }

- name: iosxr section
  hosts: iosxr 
  gather_facts: false
  roles:
    - { role: get_iosxr_command, when: "'iosxr' in groups and inventory_hostname in groups['iosxr']" }  
    - { role: save_cisco_command_logdir, when: "'iosxr' in groups and inventory_hostname in groups['iosxr']" }  

- name: nxos section
  hosts: nxos
  gather_facts: false
  roles:
    - { role: get_nxos_command, when: "'nxos' in groups and inventory_hostname in groups['nxos']" }  
    - { role: save_cisco_command_logdir, when: "'nxos' in groups and inventory_hostname in groups['nxos']" }  
