- name: create time      # ログ保存日時ディレクトリ作成
  set_fact:
    exe_date: "{{ lookup('pipe', 'date +%Y%m%d_%H%M_%S') }}"
  run_once: true

- name: create parent directory variable
  set_fact:
    logdir_date: "{{ inventory_dir }}/log/log_{{ exe_date }}"
  run_once: true

- name: create directory for log      # ログ保存用実行日時別ディレクトリ作成
  file:
    path: "{{ logdir_date }}/"
    state: directory
  register: logdir
  delegate_to: localhost
  run_once: true

- name: create directory for repository   # リポジトリ保存用ディレクトリ作成
  file:
    path: repository_dir
    state: directory
  register: repodir
  delegate_to: localhost
  run_once: true
