---
- name: save config per commands to repository dir
  copy:
    content: "{{ item.stdout }}"
    dest: "{{ repository_dir }}/{{ inventory_hostname }}_{{ item.item.file_name }}.log"
  loop: "{{ results }}"
  delegate_to: localhost
  no_log: True
