---
- name: get iosxr_command_show
  iosxr_command:
    commands: "{{ item }}" 
  register: show_result
  loop: "{{ lookup('file', 'files/{{ commands_show }}').splitlines() }}"
  
- name: set show results
  set_fact:
    show_results: "{{ show_result.results }}"

- name: get iosxr_command_route
  iosxr_command:
    commands: "{{ item }}"
  register: route_result
  loop: "{{ lookup('file', 'files/{{ commands_route }}').splitlines() }}"

- name: set route results
  set_fact:
    route_results: "{{ route_result.results }}"
