network:
  ethernets:
    ens9:
      dhcp4: false
      addresses:
        - 10.10.20.182/24
      gateway4: 10.10.20.254
      #gateway6: 2001:db8:2005::1
#        #nameservers:
#        #addresses:
  version: 2
